# Working with Vectors

### Creating Vectors and Extracting Values

In [2]:
import numpy as np

In [3]:
# Basic creation with np.array
list_of_nums = [4, 8, 15, 16, 23, 42]
array = np.array(list_of_nums)
print(type(array))

<class 'numpy.ndarray'>


In [4]:
print(array)

[ 4  8 15 16 23 42]


In [5]:
# Extracting values
first_element = array[0]
last_element = array[5]

In [6]:
first_element, last_element

(4, 42)

In [7]:
# Setting values
array[0] = 0
array[-1] = 100
print(array)

[  0   8  15  16  23 100]


In [8]:
# Creating vectors with np.arange
sequential_numbers = np.arange(17, 35, 3.5)
print(sequential_numbers)

[17.  20.5 24.  27.5 31.  34.5]


### Basic Operations

In [9]:
first = np.arange(1, 5)
second = np.array([6, 8, 3, 2])

# Addition
summation = first + second
print("Sum: ", summation)

# Subtraction
difference = first - second
print("Difference: ", difference)

# Multiplication
multiplication = first * second
print("Multiplication: ", multiplication)

# Division
division = np.around(first / second, 3)
print("Division: ", division)

# Exponentiation 
exponentiation = first ** second
print("Exponentiation: ", exponentiation)

Sum:  [ 7 10  6  6]
Difference:  [-5 -6  0  2]
Multiplication:  [ 6 16  9  8]
Division:  [0.167 0.25  1.    2.   ]
Exponentiation:  [  1 256  27  16]


### NumPy Datatypes

In [59]:
# What datatypes does numpy have?
array = np.array([4, 8, 15, 16, 23, 42])
array.dtype

# numpy.int32
# numpy.float32
# numpy.uint16
# numpy.complex64

dtype('int32')

In [78]:
# We can specify the dtype under the creation of an array
array = np.array([-4, 8, 15, 16, 23, 42], dtype=np.uint8)
array.dtype
array # Be careful
# In most cases where performance is not an issue, you can let NumPy worry about the types.

array([252,   8,  15,  16,  23,  42], dtype=uint8)

In [77]:
# Size of a vector
print(array.size) # Does the same as length, but we should use this for higher dimensional arrays

# Number of bytes
print(array.nbytes)

6
24


### Slicing

In [11]:
array = np.array([4, 8, 15, 16, 23, 42])

In [12]:
# Everything after an index:
print(array[3:])

[16 23 42]


In [84]:
# Everything before an index
print(array[:4])

[ 4  8 15 16]


In [85]:
# Between to indexes
print(array[2:5]) # Not inclusive on the last one

[15 16 23]


In [86]:
# Use a step
print(array[:5:2]) # Every other number

[ 4 15 23]


In [88]:
# Can use negative numbers
print(array[2:-2])

[15 16]


In [96]:
# Reverse an array?
reverse_array = array[::-1]
print(reverse_array)

[42 23 16 15  8  4]


### Sorting

In [101]:
# There ways to sort things in NumPy:
array = np.array([4, 15, 15, 8, 42, 23])

# 1) arr.sort() is a method for in-place sorting
array.sort()
print(array)

[ 4  8 15 15 23 42]


In [104]:
# 2) np.sort() is a function for returning a sorted copy
array = np.array([4, 15, 15, 8, 42, 23])
sorted_array = np.sort(array, kind="heapsort")
print(sorted_array)

[ 4  8 15 15 23 42]


### Copies vs. Views

In [114]:
# Reverse an array
array = np.array([-4, 8, 15, 16, 23, 42])
reverse_array = array[::-1]

# Modifying the reverese
reverse_array[0] = 1000000
print("Modified reverse: ", reverse_array)

# The original?
print("Original array: ", array) # IT IS ALSO CHANGED!

## Slicing creates a "View". This means that modifications of the view changes the original.

Modifyed reverse:  [1000000      23      16      15       8      -4]
Original array:  [     -4       8      15      16      23 1000000]


In [117]:
# Make a positive array
array = np.array([-4, 8, 15, 16, 23, 42])
positive_array = np.abs(array)

# Modify the positive array
positive_array[0] = 1000000
print("Positive array: ", positive_array)

# The original?
print("Original array: ", array) # IT IS NOT CHANGED!

# np.abs() created a "Copy". This means that modifications of the view changes the original.

Positive array:  [1000000       8      15      16      23      42]
Original array:  [-4  8 15 16 23 42]


### Aggregate functions

In [126]:
array = np.array([4, 8, 15, 16, 23, 42])

# Sum
sum_of_array = np.sum(array)

# Mean
mean_of_array = np.mean(array)

# Prod
prod_of_array = np.prod(array)

7418880

In [131]:
# Max/Min
print("Max: ", np.max(array))
print("Min: ", np.min(array))

# Argmin/Argmax
print("Argmax: ", np.argmax(array))
print("Argmin: ", np.argmin(array))

Max:  42
Min:  4
Argmax:  5
Argmin:  0
